/* Programme Padel — bibliothèque d'exercices (fiches + schémas) */
"use strict";
const DB2={t:"db",at:["hN","hF"]};
const QUAD={t:70,ln:[0,-90],lf:[4,-90],fn:-90,ff:-90,an:[0,0],af:[3,0]};
const EX={
/* ---------- FORCE ---------- */
squat_goblet:{n:"Squat goblet",c:"Force",m:["Quadriceps","Fessiers","Gainage"],
 w:"Base de toutes tes positions basses : défense, volées basses, sorties de vitre.",
 s:["Tiens un haltère ou une kettlebell contre la poitrine, coudes sous la charge.","Pieds un peu plus larges que les hanches, pointes légèrement ouvertes.","Descends en 3 secondes en poussant les hanches en arrière et les genoux vers l'extérieur.","Descends au moins jusqu'à ce que les cuisses soient parallèles au sol, puis remonte en poussant dans tout le pied."],
 k:["Poitrine haute, regard devant","Talons collés au sol","Genoux dans l'axe des pieds"],e:["Genoux qui rentrent vers l'intérieur","Dos qui s'arrondit en bas","Talons qui décollent"],
 ez:"Squat sur une chaise : tu t'assois et te relèves.",hd:"Pause de 2 s en bas.",
 fig:[{p:P({an:[12,172],af:[18,172]}),pr:[{t:"kb"}],l:"Départ"},{p:P({t:30,ln:[82,-22],lf:[76,-18],an:[35,176],af:[40,176]}),pr:[{t:"kb"}],ar:[{at:"hip",o:[-18,-14],d:[0,26]}],l:"En bas : cuisses parallèles"}]},
back_squat:{n:"Back squat (squat barre)",c:"Force",m:["Quadriceps","Fessiers","Lombaires"],
 w:"Le meilleur exercice pour la force des jambes : premiers pas plus rapides, smashs plus puissants.",
 s:["Place la barre sur le haut du dos (trapèzes), mains un peu plus larges que les épaules.","Sors du rack en deux pas, pieds largeur d'épaules.","Inspire, gaine le ventre, puis descends hanches en arrière et genoux vers l'extérieur.","Descends jusqu'à la parallèle, puis remonte en gardant le même angle de dos."],
 k:["Bloque ta respiration pendant chaque répétition","Barre au-dessus du milieu du pied","Règle les sécurités du rack"],e:["Fesses qui montent avant les épaules","Genoux qui rentrent","Charge trop lourde au détriment de la profondeur"],
 ez:"Squat goblet.",hd:"Pause de 1 s en bas.",
 fig:[{p:P({t:4,an:[-35,150],af:[-30,150]}),pr:[{t:"plate",at:"shN",dx:-3,dy:-2}],l:"Départ"},{p:P({t:42,ln:[88,-25],lf:[82,-22],an:[7,-168],af:[12,-168]}),pr:[{t:"plate",at:"shN",dx:-3,dy:-2}],ar:[{at:"hip",o:[-20,-16],d:[0,26]}],l:"En bas"}]},
contrast_squat:{n:"Squat + sauts (contraste)",c:"Explosivité",m:["Quadriceps","Fessiers","Mollets"],
 w:"Les squats lourds réveillent le système nerveux : les sauts juste après sont plus puissants. C'est ce qui transforme ta force en explosivité.",
 s:["Fais 3 squats lourds (RPE 8).","Pose la barre et va dans un espace libre, en 20 s maximum.","Enchaîne 3 sauts verticaux maximaux avec balancier des bras.","Récupère 3 min avant la série suivante."],
 k:["Chaque saut doit être maximal","Réception souple, genoux fléchis"],e:["Attendre trop longtemps entre squat et sauts","Continuer quand les sauts ralentissent"],
 ez:"Squat goblet + 3 sauts.",hd:"Sauts sur une box haute.",
 fig:[{p:P({t:42,ln:[88,-25],lf:[82,-22],an:[7,-168],af:[12,-168]}),pr:[{t:"plate",at:"shN",dx:-3,dy:-2}],l:"1. Trois squats lourds"},{p:P({t:4,ln:[4,-6],lf:[0,-10],an:[170,175],af:[165,172],fn:40,ff:40,air:24}),ar:[{at:"hip",o:[-22,10],d:[0,-30]}],l:"2. Trois sauts max"}]},
rdl:{n:"Soulevé de terre roumain",c:"Force",m:["Ischio-jambiers","Fessiers","Lombaires"],
 w:"Protège tes ischios pendant les sprints et les fentes, et renforce le bas du dos sollicité par les rotations.",
 s:["Debout, un haltère dans chaque main devant les cuisses, genoux légèrement fléchis.","Pousse les hanches vers l'arrière comme pour fermer une porte avec les fesses.","Les haltères glissent le long des cuisses puis des tibias, dos plat.","Descends jusqu'à sentir l'étirement derrière les cuisses (souvent mi-tibia), puis remonte en serrant les fessiers."],
 k:["Le mouvement vient des hanches","Genoux quasi fixes","Charges collées aux jambes"],e:["Dos rond","Plier les genoux comme un squat","Haltères qui s'éloignent des jambes"],
 ez:"Sans charge, un bâton le long du dos.",hd:"Sur une jambe.",
 fig:[{p:P({t:2}),pr:[DB2],l:"Départ"},{p:P({t:78,ln:[12,-2],lf:[10,-2]}),pr:[DB2],ar:[{at:"hip",o:[-12,-14],d:[-22,0]}],l:"Hanches en arrière, dos plat"}]},
trapbar:{n:"Soulevé de terre trap bar",c:"Force",m:["Fessiers","Quadriceps","Ischios","Dos"],
 w:"Force de tout le corps en une seule poussée, plus facile à apprendre et moins dur pour le dos que le soulevé de terre classique.",
 s:["Place-toi au centre de la barre hexagonale, pieds largeur de hanches.","Descends en fléchissant hanches et genoux, saisis les poignées bras tendus.","Dos plat, poitrine sortie, inspire et gaine.","Pousse le sol avec les jambes jusqu'à être debout, puis redescends en contrôlant."],
 k:["Pousse le sol plutôt que de tirer la barre","Bras tendus comme des câbles"],e:["Dos rond au départ","Hanches qui montent avant les épaules"],
 ez:"Poignées hautes.",hd:"Monte le plus vite possible (bloc 3).",
 fig:[{p:P({t:48,ln:[72,-18],lf:[66,-15]}),pr:[{t:"plate",at:"hN"}],l:"Départ"},{p:P({t:0}),pr:[{t:"plate",at:"hN"}],ar:[{at:"hip",o:[-24,20],d:[0,-28]}],l:"Debout, hanches tendues"}]},
lunge_back:{n:"Fentes arrière",c:"Force",m:["Quadriceps","Fessiers","Adducteurs"],
 w:"Reproduit tes appuis décalés (volée basse, récupération d'amortie) et équilibre tes deux jambes.",
 s:["Debout, haltères le long du corps.","Fais un grand pas en arrière et pose l'avant du pied.","Descends jusqu'à ce que le genou arrière frôle le sol, genou avant au-dessus de la cheville.","Pousse sur le talon avant pour revenir debout. Alterne."],
 k:["Buste droit","Poids surtout sur la jambe avant"],e:["Genou avant qui rentre","Pas trop court"],
 ez:"Sans charge, une main sur un support.",hd:"Pied avant surélevé sur un step.",
 fig:[{p:P({}),pr:[DB2],l:"Départ"},{p:P({t:4,ln:[88,0],lf:[-8,-100],ff:20}),pr:[DB2],ar:[{at:"hip",o:[-16,-18],d:[0,24]}],l:"Genou arrière frôle le sol"}]},
jump_lunge:{n:"Fentes sautées alternées",c:"Explosivité",m:["Quadriceps","Fessiers","Mollets"],
 w:"Explosivité en position décalée et changement d'appuis rapide, comme sur une récupération au filet.",
 s:["Pars en fente, bras opposés à la jambe avant.","Saute verticalement en poussant sur les deux jambes.","Inverse les jambes en l'air.","Réceptionne-toi en fente, souple et silencieux, et enchaîne."],
 k:["Réception silencieuse","Buste droit"],e:["Genou arrière qui tape le sol","Réceptions raides"],
 ez:"Fente arrière dynamique sans saut.",hd:"Enchaîner avec un contact au sol plus court.",
 fig:[{p:P({t:4,ln:[88,0],lf:[-8,-100],ff:20,an:[40,70],af:[-40,-20]}),l:"Fente"},{p:P({t:2,ln:[40,-30],lf:[-25,-60],ff:10,an:[-30,-10],af:[40,70],air:24}),ar:[{at:"hip",o:[-26,10],d:[0,-26]}],l:"Saut + changement de jambe"}]},
bulgarian:{n:"Split squat bulgare",c:"Force",m:["Quadriceps","Fessiers","Adducteurs","Équilibre"],
 w:"Force sur une jambe, comme quand tu pousses sur le terrain. Corrige aussi les écarts entre jambe droite et gauche.",
 s:["Dos à un banc, pose le dessus du pied arrière dessus.","Avance le pied avant assez loin pour que le genou reste au-dessus de la cheville en bas.","Descends droit jusqu'à ce que la cuisse avant soit parallèle au sol.","Remonte en poussant sur le talon avant. Toutes les répétitions d'une jambe, puis change."],
 k:["Buste légèrement penché en avant","Hanches de face"],e:["Pied avant trop près du banc","Pousser avec la jambe arrière"],
 ez:"Sans charge, une main sur un support.",hd:"Descente en 3 s.",
 fig:[{p:P({t:6,ln:[8,-4],lf:[-30,-73],ff:-100}),pr:[DB2,{t:"block",at:"aF",dx:-30,w:34,dy:3}],l:"Pied arrière sur le banc"},{p:P({t:10,ln:[82,-8],lf:[-12,-133],ff:-100}),pr:[DB2,{t:"block",at:"aF",dx:-30,w:34,dy:3}],ar:[{at:"hip",o:[-18,-18],d:[0,24]}],l:"Descends droit"}]},
row_db:{n:"Rowing haltère un bras",c:"Force",m:["Grand dorsal","Rhomboïdes","Biceps"],
 w:"Équilibre les muscles de devant sollicités par les frappes et stabilise l'omoplate pour protéger l'épaule.",
 s:["Une main (et éventuellement un genou) en appui sur un banc, dos plat.","L'autre bras pend avec l'haltère sous l'épaule.","Tire le coude vers le plafond, près du corps, jusqu'aux côtes.","Serre l'omoplate 1 s en haut, puis redescends lentement."],
 k:["Le dos ne tourne pas","Tire avec le coude, pas avec la main"],e:["Rotation du buste pour aider","Épaule qui monte vers l'oreille"],
 ez:"Rowing à l'élastique debout.",hd:"Pause de 2 s en haut.",
 fig:[{p:P({t:80,ln:[18,-2],lf:[-18,2],af:[8,6]}),pr:[{t:"db",at:"hN"},{t:"block",at:"hF",dx:-6,w:30,dy:3}],l:"Bras tendu"},{p:P({t:80,ln:[18,-2],lf:[-18,2],an:[-150,0],af:[8,6]}),pr:[{t:"db",at:"hN"},{t:"block",at:"hF",dx:-6,w:30,dy:3}],ar:[{at:"hN",o:[-16,20],d:[0,-22]}],l:"Coude vers le plafond"}]},
bench_db:{n:"Développé couché haltères",c:"Force",m:["Pectoraux","Triceps","Épaules"],
 w:"Puissance de poussée pour les volées et les frappes à plat. Les haltères laissent l'épaule bouger naturellement.",
 s:["Allongé sur un banc, pieds au sol, haltères au-dessus de la poitrine bras tendus.","Omoplates serrées et abaissées.","Descends les haltères sur les côtés de la poitrine, coudes à environ 45° du corps.","Pousse vers le haut en rapprochant légèrement les haltères."],
 k:["Coudes à 45°, pas à 90°","Descente contrôlée en 2 s"],e:["Coudes trop écartés","Fesses qui décollent du banc"],
 ez:"Pompes.",hd:"Banc incliné à 30°.",
 fig:[{p:P({t:-90,ln:[90,0],lf:[84,4],an:[180,180],af:[178,178]}),pr:[{t:"block",from:"neck",to:"hip",dy:6},DB2],l:"Bras tendus"},{p:P({t:-90,ln:[90,0],lf:[84,4],an:[40,178],af:[44,178]}),pr:[{t:"block",from:"neck",to:"hip",dy:6},DB2],ar:[{at:"hN",o:[16,-4],d:[0,18]}],l:"Haltères au niveau de la poitrine"}]},
pullup:{n:"Tractions",c:"Force",m:["Grand dorsal","Biceps","Avant-bras"],
 w:"Renforce le dos et la prise : épaule plus stable au smash et avant-bras moins fatigué.",
 s:["Suspends-toi à la barre, mains en pronation un peu plus larges que les épaules.","Abaisse les épaules (loin des oreilles) avant de tirer.","Tire jusqu'à ce que le menton passe la barre, coudes vers les hanches.","Redescends en 2–3 s jusqu'aux bras presque tendus."],
 k:["Pas de balancier","Poitrine vers la barre"],e:["Demi-répétitions","Élan avec les jambes"],
 ez:"Élastique sous les pieds, ou descentes lentes de 5 s.",hd:"Lestées avec un disque (bloc 3).",
 fig:[{p:P({ln:[10,-30],lf:[4,-28],fn:40,ff:40,an:[176,180],af:[172,180],air:30}),pr:[{t:"hbar",at:"hN",dy:-3}],l:"Suspendu, épaules basses"},{p:P({ln:[10,-30],lf:[4,-28],fn:40,ff:40,an:[25,172],af:[20,172],air:58}),pr:[{t:"hbar",at:"hN",dy:-3}],ar:[{at:"hip",o:[-24,0],d:[0,-26]}],l:"Menton au-dessus"}]},
press_1arm:{n:"Développé militaire un bras",c:"Force",m:["Épaules","Triceps","Obliques"],
 w:"Force au-dessus de la tête pour le smash et la bandeja, avec un gainage qui empêche le tronc de pencher.",
 s:["Debout, haltère à hauteur d'épaule, paume vers l'intérieur.","Serre les fessiers et le ventre.","Pousse l'haltère au-dessus de la tête jusqu'à tendre le bras.","Redescends en contrôlant jusqu'à l'épaule."],
 k:["Le buste ne penche pas","Côtes rentrées"],e:["Se pencher du côté opposé","Cambrer le bas du dos"],
 ez:"Assis, dos contre un dossier.",hd:"En demi-genou.",
 fig:[{p:P({an:[-20,165]}),pr:[{t:"db",at:"hN"}],l:"Haltère à l'épaule"},{p:P({an:[178,180]}),pr:[{t:"db",at:"hN"}],ar:[{at:"shN",o:[18,-8],d:[0,-26]}],l:"Bras tendu"}]},
push_press:{n:"Push press haltères",c:"Explosivité",m:["Jambes","Épaules","Triceps"],
 w:"Transmet la force des jambes vers les bras : c'est la chaîne du smash.",
 s:["Debout, haltères aux épaules, pieds largeur de hanches.","Petite flexion rapide des genoux (10–15 cm), buste droit.","Pousse avec les jambes et enchaîne en envoyant les haltères au-dessus de la tête.","Stabilise bras tendus, puis redescends aux épaules."],
 k:["La poussée vient des jambes","Flexion courte et rapide"],e:["Flexion trop profonde","Talons qui décollent pendant la flexion"],
 ez:"Développé militaire strict.",hd:"Plus lourd, toujours explosif.",
 fig:[{p:P({t:3,ln:[28,-28],lf:[25,-25],an:[-20,165],af:[-15,165]}),pr:[DB2],ar:[{at:"hip",o:[-22,-6],d:[0,14]}],l:"1. Petite flexion"},{p:P({an:[178,180],af:[176,180],fn:45,ff:45,air:4}),pr:[DB2],ar:[{at:"hip",o:[-22,10],d:[0,-28]}],l:"2. Poussée jambes + bras"}]},
landmine:{n:"Rotation landmine",c:"Explosivité",m:["Obliques","Hanches","Épaules"],
 w:"Rotation puissante qui part des hanches : le moteur de ton coup droit, de ta víbora et de tes sorties de vitre.",
 s:["Cale une extrémité de la barre dans un coin (ou un support landmine), tiens l'autre à deux mains, bras tendus.","Pieds largeur d'épaules, genoux légèrement fléchis.","Amène la barre vers une hanche en pivotant le pied arrière et les hanches.","Ramène-la en arc de cercle vers l'autre hanche, en passant devant le visage."],
 k:["Les hanches lancent, les bras suivent","Bras quasi tendus"],e:["Tourner uniquement avec les bras","Dos qui s'arrondit"],
 ez:"Rotation à l'élastique.",hd:"Version explosive : accélère au centre.",
 fig:[{top:{rot:-35,to:[-30,-22],bar:[0,-86]},l:"Barre vers la hanche gauche"},{top:{rot:35,to:[30,-22],bar:[0,-86],ar:[[[-26,-6],[26,-6],[0,14]]]},l:"Arc vers la hanche droite"}]},
/* ---------- GAINAGE ---------- */
pallof:{n:"Pallof press",c:"Gainage",m:["Obliques","Transverse"],
 w:"Apprend au tronc à résister à la rotation : plus de stabilité sur les frappes et un dos protégé.",
 s:["Accroche un élastique ou une poulie à hauteur de poitrine et place-toi de profil.","Poignée à deux mains contre le sternum, pieds largeur d'épaules.","Pousse les mains droit devant toi sans laisser le buste tourner vers l'ancrage.","Tiens 2 s puis ramène. Change de côté. Bloc 2 : reste bras tendus 20 s. Bloc 3 : fais des pas chassés bras tendus."],
 k:["Le buste reste face devant","Respire normalement"],e:["Se laisser tirer vers l'ancrage","Se cambrer"],
 ez:"Élastique plus léger.",hd:"Version en marchant (bloc 3).",
 fig:[{top:{rot:0,to:[0,-14],band:[84,-14]},l:"Mains au sternum"},{top:{rot:0,to:[0,-44],band:[84,-14],ar:[[[-14,-16],[-14,-42]]]},l:"Bras tendus, le buste ne tourne pas"}]},
plank:{n:"Gainage planche",c:"Gainage",m:["Abdominaux","Transverse"],
 w:"Un tronc solide transmet la force des jambes aux bras et protège le dos quand tu tournes.",
 s:["Appui sur les avant-bras, coudes sous les épaules.","Jambes tendues, pointes de pied au sol.","Serre fessiers et ventre, bassin légèrement rentré.","Garde une ligne droite de la tête aux talons."],
 k:["Respire calmement","Pousse le sol avec les avant-bras"],e:["Fesses trop hautes","Bas du dos qui se creuse"],
 ez:"Genoux au sol.",hd:"Lève un pied 2 s en alternance.",
 fig:[{p:P({t:90,ln:[-76,-76],lf:[-76,-76],fn:0,ff:0,an:[0,90],af:[0,90]}),l:"Ligne droite tête-talons"}]},
side_plank:{n:"Gainage latéral",c:"Gainage",m:["Obliques","Moyen fessier"],
 w:"Stabilité latérale pour les pas chassés et les frappes en déséquilibre.",
 s:["Allongé sur le côté, coude sous l'épaule, jambes tendues l'une sur l'autre.","Soulève les hanches pour aligner le corps.","Bras du dessus sur la hanche ou vers le plafond.","Tiens le temps indiqué, puis change de côté."],
 k:["Hanches hautes","Épaule loin de l'oreille"],e:["Hanches qui tombent","Bassin qui part en arrière"],
 ez:"Genoux au sol.",hd:"Lève la jambe du dessus.",
 fig:[{p:P({t:75,ln:[-75,-75],lf:[-75,-75],fn:15,ff:15,an:[0,90],anS:[1,0.4],af:[178,178]}),ar:[{at:"hip",o:[0,16],d:[0,-12]}],l:"Corps aligné, hanches hautes"}]},
side_plank_rot:{n:"Planche latérale avec rotation",c:"Gainage",m:["Obliques","Épaules"],
 w:"Ajoute une rotation contrôlée au gainage latéral, proche de la rotation des frappes.",
 s:["Planche latérale sur l'avant-bras, bras du dessus vers le plafond.","Passe lentement la main du dessus sous ton corps en tournant le buste vers le sol.","Reviens en ouvrant la poitrine, bras vers le plafond.","Les hanches restent hautes tout le long."],
 k:["Mouvement lent","Regarde ta main"],e:["Hanches qui tombent pendant la rotation"],
 ez:"Genoux au sol.",hd:"Petit haltère dans la main.",
 fig:[{p:P({t:75,ln:[-75,-75],lf:[-75,-75],fn:15,ff:15,an:[0,90],anS:[1,0.4],af:[178,178]}),l:"Bras vers le plafond"},{p:P({t:75,ln:[-75,-75],lf:[-75,-75],fn:15,ff:15,an:[0,90],anS:[1,0.4],af:[-20,-40]}),ar:[{at:"shF",o:[10,-30],d:[-10,34],c:[18,10]}],l:"Main sous le corps"}]},
dead_bug:{n:"Dead bug",c:"Gainage",m:["Abdominaux profonds"],
 w:"Apprend à bouger bras et jambes sans que le bas du dos décolle : la base d'un tronc stable.",
 s:["Allongé sur le dos, bras tendus vers le plafond, hanches et genoux à 90°.","Plaque le bas du dos au sol.","Tends en même temps un bras vers l'arrière et la jambe opposée vers l'avant, sans toucher le sol.","Reviens et alterne."],
 k:["Expire en tendant","Lent : 3 s par répétition"],e:["Bas du dos qui se creuse","Aller trop vite"],
 ez:"Seulement les jambes.",hd:"Tiens un élastique tendu.",
 fig:[{p:P({t:-90,ln:[180,90],lf:[178,92],fn:180,ff:180,an:[180,180],af:[178,178]}),l:"Départ : table"},{p:P({t:-90,ln:[95,95],lf:[178,92],fn:180,ff:180,an:[180,180],af:[-95,-95]}),ar:[{at:"kN",o:[4,-14],d:[22,0]}],l:"Bras et jambe opposés tendus"}]},
shoulder_tap:{n:"Planche avec toucher d'épaule",c:"Gainage",m:["Abdominaux","Obliques","Épaules"],
 w:"Anti-rotation en appui sur les mains : stabilité du tronc et des épaules.",
 s:["Position de pompe, mains sous les épaules, pieds un peu écartés.","Lève une main et touche l'épaule opposée.","Repose et alterne.","Le bassin ne doit pas tanguer."],
 k:["Pieds écartés = plus facile","Fessiers serrés"],e:["Bassin qui bascule","Fesses hautes"],
 ez:"Genoux au sol.",hd:"Pieds serrés.",
 fig:[{p:P({t:80,ln:[-62,-62],lf:[-62,-62],fn:0,ff:0}),l:"Position de pompe"},{p:P({t:80,ln:[-62,-62],lf:[-62,-62],fn:0,ff:0,af:[60,-100]}),l:"Main à l'épaule opposée"}]},
pushup:{n:"Pompes",c:"Force",m:["Pectoraux","Triceps","Gainage"],
 w:"Test de force-endurance du haut du corps.",
 s:["Mains un peu plus larges que les épaules, corps aligné.","Descends la poitrine à un poing du sol, coudes à 45°.","Pousse jusqu'aux bras tendus.","Pendant le test : pas de pause de plus de 2 s en haut."],
 k:["Corps gainé"],e:["Bassin qui tombe","Demi-répétitions"],ez:"Mains sur un banc.",hd:"Pieds surélevés.",
 fig:[{p:P({t:80,ln:[-62,-62],lf:[-62,-62],fn:0,ff:0}),l:"Bras tendus"},{p:P({t:88,ln:[-72,-72],lf:[-72,-72],fn:0,ff:0,an:[-70,0],af:[-70,0]}),ar:[{at:"neck",o:[10,-22],d:[0,14]}],l:"Poitrine à un poing du sol"}]},
/* ---------- PRÉVENTION ---------- */
ext_rot:{n:"Rotation externe épaule à l'élastique",c:"Prévention",m:["Coiffe des rotateurs"],
 w:"La coiffe des rotateurs freine le bras après chaque smash et bandeja. C'est la protection n°1 de l'épaule du joueur de gauche.",
 s:["Élastique accroché à hauteur de coude, place-toi de profil.","Coude collé au corps (serviette roulée entre coude et flanc), coude à 90°, avant-bras vers l'avant.","Tourne l'avant-bras vers l'extérieur en gardant le coude contre toi.","Reviens lentement en 2 s."],
 k:["Coude fixe","Mouvement lent"],e:["Décoller le coude","Tourner le buste"],ez:"Élastique plus léger.",hd:"Pause de 2 s en fin de rotation.",
 fig:[{top:{rot:0,arms:[{s:1,pts:[[21,4],[22,-22]]}],band:[-80,-22]},l:"Avant-bras vers l'avant"},{top:{rot:0,arms:[{s:1,pts:[[21,4],[45,-8]]}],band:[-80,-22],ar:[[[30,-28],[48,-18],[44,-30]]]},l:"Rotation vers l'extérieur"}]},
ext_rot90:{n:"Rotation externe à 90°",c:"Prévention",m:["Coiffe des rotateurs"],
 w:"Renforce l'épaule dans la position exacte du smash et de la bandeja.",
 s:["Élastique accroché devant toi à hauteur d'épaule.","Coude levé à hauteur d'épaule sur le côté, plié à 90°, avant-bras vers l'avant.","Fais pivoter l'avant-bras vers le haut jusqu'à la verticale, sans bouger le coude.","Reviens lentement."],
 k:["Coude à hauteur d'épaule","Omoplate serrée"],e:["Coude qui descend","Dos cambré"],ez:"Allongé sur le dos avec 1 kg.",hd:"Tenir 3 s en haut.",
 fig:[{p:P({an:[88,90],anS:[0.35,1]}),pr:[{t:"band",from:"hN",d:[50,0]}],l:"Avant-bras vers l'avant"},{p:P({an:[88,180],anS:[0.35,1]}),pr:[{t:"band",from:"hN",d:[56,24]}],ar:[{at:"eN",o:[14,-2],d:[-6,-22],c:[6,-18]}],l:"Avant-bras vertical"}]},
ytw:{n:"Y-T-W sur banc incliné",c:"Prévention",m:["Trapèzes inférieurs","Rhomboïdes","Coiffe"],
 w:"Renforce les muscles qui tiennent l'omoplate : une omoplate stable protège l'épaule malgré le volume de smashs.",
 s:["Allongé sur le ventre sur un banc incliné à 30–45°, un petit haltère (2–4 kg) par main, bras pendants.","Y : lève les bras en diagonale au-dessus de la tête, pouces vers le plafond.","T : lève les bras sur les côtés, à l'horizontale.","W : tire les coudes vers les hanches, mains vers l'extérieur. Tiens 1 s en haut de chaque lettre."],
 k:["Omoplates vers le bas et l'arrière","Charges très légères"],e:["Hausser les épaules","Prendre de l'élan"],ez:"Sans charge.",hd:"Tenir 3 s.",
 fig:[{top:{rot:0,body:true,arms:[{s:-1,pts:[[-44,-46]]},{s:1,pts:[[44,-46]]}]},l:"Y"},{top:{rot:0,body:true,arms:[{s:-1,pts:[[-62,2]]},{s:1,pts:[[62,2]]}]},l:"T"},{top:{rot:0,body:true,arms:[{s:-1,pts:[[-34,22],[-48,-4]]},{s:1,pts:[[34,22],[48,-4]]}]},l:"W"}]},
copenhagen:{n:"Copenhagen plank",c:"Prévention",m:["Adducteurs","Obliques"],
 w:"Les adducteurs sont très exposés sur les grands écarts en défense. Cet exercice réduit fortement le risque de blessure à l'aine.",
 s:["Allongé sur le côté, avant-bras au sol sous l'épaule.","Pose l'intérieur du pied (ou du genou, plus facile) de la jambe du dessus sur un banc.","Soulève les hanches pour aligner le corps ; la jambe du dessous vient sous le banc.","Tiens le temps indiqué, puis change de côté."],
 k:["Corps aligné","Pousse le banc avec la jambe du dessus"],e:["Hanches qui s'affaissent","Épaule qui s'écrase"],ez:"Genou sur le banc au lieu du pied.",hd:"Monte et descends les hanches lentement.",
 fig:[{p:P({t:115,ln:[-88,-88],lf:[-70,-40],fn:-90,ff:0,an:[0,90],anS:[1,0.4],af:[40,-150]}),pr:[{t:"block",at:"aN",dx:-16,w:26,dy:4}],l:"Départ : hanches basses"},{p:P({t:100,ln:[-100,-100],lf:[-97,-100],fn:-90,ff:-90,an:[0,90],anS:[1,0.4],af:[40,-150]}),pr:[{t:"block",at:"aN",dx:-16,w:26,dy:4}],ar:[{at:"hip",o:[0,22],d:[0,-14]}],l:"Hanches levées, corps aligné"}]},
calf_ecc:{n:"Mollets excentriques",c:"Prévention",m:["Mollets","Tendon d'Achille"],
 w:"Le padel enchaîne démarrages et freinages sur l'avant du pied. Renforcer le tendon d'Achille protège aussi les chevilles.",
 s:["Avant du pied sur une marche, talons dans le vide, une main sur un mur.","Monte sur la pointe des pieds avec les deux jambes.","Passe sur une seule jambe et redescends lentement en 3 s, talon sous le niveau de la marche.","Remonte à deux jambes et recommence."],
 k:["Descente lente","Amplitude complète"],e:["Descente rapide","Rebondir en bas"],ez:"Descente sur deux jambes.",hd:"Un pied tout le long, puis avec un haltère.",
 fig:[{p:P({fn:30,ff:30,base:16}),pr:[{t:"block",at:"tN",dx:-7,w:36,dy:0}],l:"Sur la pointe"},{p:P({fn:120,ff:120,base:12}),pr:[{t:"block",at:"tN",dx:-7,w:36,dy:0}],ar:[{at:"aN",o:[-16,-30],d:[0,24]}],l:"Talon sous la marche, en 3 s"}]},
/* ---------- EXPLOSIVITÉ ---------- */
rope:{n:"Corde à sauter",c:"Explosivité",m:["Mollets","Chevilles","Cardio"],
 w:"Rend tes appuis légers et réactifs, travaille les chevilles et le cardio.",
 s:["Coudes près du corps, poignées à hauteur de hanches.","La corde tourne grâce aux poignets, pas aux épaules.","Petits sauts sur l'avant du pied, 2–3 cm au-dessus du sol.","Varie : pieds joints, alternés, pas chassés sur place."],
 k:["Genoux souples","Regard devant"],e:["Sauter trop haut","Atterrir sur les talons"],ez:"Sans corde, même rythme.",hd:"Double rythme ou double saut.",
 fig:[{p:P({fn:40,ff:40,an:[15,70],af:[18,70],air:5}),pr:[{t:"rope"}],l:"Petits rebonds sur l'avant du pied"}]},
pogo:{n:"Pogo jumps",c:"Explosivité",m:["Mollets","Tendon d'Achille"],
 w:"Améliore la réactivité de la cheville : tu rebondis mieux, ton split-step est plus rapide.",
 s:["Debout, genoux presque tendus, sur l'avant du pied.","Rebondis sur place en utilisant surtout les chevilles.","Contact au sol le plus court possible, comme sur un sol brûlant.","Garde un rythme régulier."],
 k:["Chevilles fermes comme un ressort","Bras qui accompagnent"],e:["Plier les genoux","Talons qui touchent"],ez:"Rebonds plus bas.",hd:"Sur une jambe.",
 fig:[{p:P({fn:40,ff:40,an:[10,80],af:[12,80],air:14}),ar:[{at:"aN",o:[-18,-4],d:[0,-14]}],l:"En l'air, chevilles verrouillées"},{p:P({fn:48,ff:48,ln:[3,-3],an:[10,80],af:[12,80]}),ar:[{at:"aN",o:[-18,-20],d:[0,14]}],l:"Contact bref sur l'avant du pied"}]},
box_jump:{n:"Box jump",c:"Explosivité",m:["Quadriceps","Fessiers","Mollets"],
 w:"Puissance verticale sans l'impact d'une réception au sol : idéal pour apprendre à sauter en protégeant les genoux.",
 s:["Face à une box (40–60 cm), pieds largeur de hanches.","Descends vite en quart de squat, bras en arrière.","Saute en projetant les bras vers l'avant et le haut.","Réceptionne-toi sur la box en demi-squat, souple, puis redescends en marchant."],
 k:["Réception silencieuse","Hauteur modérée"],e:["Box trop haute","Sauter en bas de la box"],ez:"Box plus basse.",hd:"Départ assis sur un banc.",
 fig:[{p:P({t:40,ln:[70,-22],lf:[66,-20],an:[-45,-40],af:[-50,-45]}),pr:[{t:"box",at:"aN",dx:34,w:40,h:34}],l:"Armer : bras en arrière"},{p:P({t:25,ln:[60,-20],lf:[56,-18],an:[70,80],af:[65,80],base:34}),pr:[{t:"box",at:"aN",dx:-18,w:40,h:34}],l:"Réception souple sur la box"}]},
skater:{n:"Skater jumps (bonds latéraux)",c:"Explosivité",m:["Fessiers","Adducteurs","Chevilles"],
 w:"Poussées latérales et réceptions stables sur une jambe : le déplacement latéral du padel.",
 s:["Debout sur la jambe droite, légèrement fléchie.","Pousse fort latéralement vers la gauche.","Réceptionne-toi sur la jambe gauche seulement, l'autre passe derrière.","Stabilise 1 s (2 s en bloc 2), puis repars de l'autre côté."],
 k:["Genou dans l'axe du pied à la réception","Buste stable"],e:["Genou qui rentre","Enchaîner sans stabiliser"],ez:"Grand pas latéral sans saut.",hd:"Plus loin, stabilisation immédiate.",
 fig:[{p:P({view:"front",t:-8,ln:[-18,6],lf:[-12,-52],an:[-40,-20],af:[40,70]}),l:"Réception sur une jambe"},{p:P({view:"front",t:8,ln:[12,52],lf:[18,-6],an:[-40,-70],af:[40,20]}),ar:[{at:"head",o:[-34,-14],d:[62,0]}],l:"Bond vers l'autre côté"}]},
mb_rot:{n:"Lancer rotatif médecine-ball",c:"Explosivité",m:["Obliques","Hanches","Épaules"],
 w:"Puissance de rotation côté coup droit et côté revers : le transfert hanches → tronc → bras de tes frappes.",
 s:["De profil à un mur, à 1–2 m, médecine-ball (3–4 kg) à deux mains.","Arme en tournant hanches et buste vers l'arrière, ballon à la hanche arrière.","Pivote le pied arrière, lance les hanches puis le buste, et projette le ballon contre le mur.","Rattrape, réarme, enchaîne. Fais les deux côtés."],
 k:["Les hanches partent en premier","Lancer à fond"],e:["Lancer seulement avec les bras","Ballon trop lourd"],ez:"Ballon de 2 kg.",hd:"Avec un pas d'élan.",
 fig:[{top:{rot:-50,to:[-30,10],ball:[-34,16],wall:70},l:"Armer : ballon à la hanche"},{top:{rot:30,to:[34,-14],ball:[60,-14],wall:70,ar:[[[-30,20],[34,4],[0,34]]]},l:"Lancer contre le mur"}]},
mb_slam:{n:"Médecine-ball slam",c:"Explosivité",m:["Abdominaux","Dos","Épaules"],
 w:"Puissance vers le bas en extension complète, proche du smash, et très bon pour le cardio.",
 s:["Debout, slam ball (ballon sans rebond) au-dessus de la tête, sur la pointe des pieds.","Écrase le ballon au sol devant tes pieds de toutes tes forces en fléchissant les hanches.","Ramasse-le dos plat.","Remonte bras tendus au-dessus de la tête et recommence."],
 k:["Extension complète en haut","Abdos serrés"],e:["Ramasser dos rond","Utiliser un ballon qui rebondit"],ez:"Ballon plus léger.",hd:"Enchaîner plus vite.",
 fig:[{p:P({fn:40,ff:40,an:[172,180],af:[168,180]}),pr:[{t:"ball",at:"hN",dy:-8}],l:"Ballon au-dessus de la tête"},{p:P({t:62,ln:[60,-20],lf:[56,-18],an:[40,40],af:[36,36]}),pr:[{t:"ball",at:"hN",dx:6,ground:true}],ar:[{at:"hN",o:[14,-24],d:[0,22]}],l:"Écrase au sol"}]},
mb_overhead:{n:"Lancer par-dessus la tête avec saut",c:"Explosivité",m:["Jambes","Tronc","Épaules"],
 w:"Toute la chaîne du smash : jambes, tronc, épaules.",
 s:["Médecine-ball de 2 kg, en extérieur ou dans un grand espace.","Descends en quart de squat en armant le ballon derrière la tête.","Saute et lance le ballon le plus loin possible devant toi.","Réceptionne-toi souplement."],
 k:["Le lancer suit l'extension des jambes","Bras tendus à la fin"],e:["Cambrer excessivement","Lancer sans les jambes"],ez:"Sans saut.",hd:"Lancer vers un mur haut.",
 fig:[{p:P({t:30,ln:[70,-22],lf:[66,-20],an:[-165,-150],af:[-170,-155]}),pr:[{t:"ball",at:"hN",dx:-2,dy:-4}],l:"Armer derrière la tête"},{p:P({t:-4,an:[140,140],af:[136,136],fn:40,ff:40,air:14}),pr:[{t:"ball",at:"hN",dx:30,dy:-22}],ar:[{at:"hN",o:[6,-4],d:[18,-12]}],l:"Saut + lancer vers l'avant"}]},
cmj:{n:"Countermovement jump (saut vertical)",c:"Explosivité",m:["Quadriceps","Fessiers","Mollets"],
 w:"Le saut le plus proche du jeu : contre-mouvement rapide puis détente. Pour les smashs et la réactivité.",
 s:["Debout, pieds largeur de hanches.","Descends vite en demi-squat en balançant les bras en arrière.","Enchaîne immédiatement un saut maximal en projetant les bras vers le haut.","Réceptionne-toi souplement, repositionne-toi avant le suivant."],
 k:["Pas de pause en bas","Chaque saut à 100 %"],e:["Pause en bas","Réception jambes tendues"],ez:"Sans les bras.",hd:"Vise un repère haut sur un mur.",
 fig:[{p:P({t:42,ln:[74,-24],lf:[70,-22],an:[-55,-50],af:[-60,-55]}),ar:[{at:"hip",o:[-22,-24],d:[0,18]}],l:"Descente rapide, bras en arrière"},{p:P({t:2,an:[172,176],af:[168,174],fn:40,ff:40,air:26}),ar:[{at:"hip",o:[-24,10],d:[0,-30]}],l:"Saut maximal"}]},
depth_jump:{n:"Depth jump",c:"Explosivité",m:["Mollets","Quadriceps"],
 w:"Apprend à rebondir vite après un impact : la base de la réactivité quand tu changes de direction.",
 s:["Debout sur une box de 30–40 cm.","Laisse-toi tomber en faisant un pas en avant (ne saute pas).","Dès que les pieds touchent le sol, rebondis le plus haut possible.","Réceptionne-toi et récupère complètement."],
 k:["Contact au sol très court","Peu de répétitions, qualité maximale"],e:["S'enfoncer trop bas à l'impact","Box trop haute"],ez:"Box plus basse.",hd:"Rebond vers l'avant.",
 fig:[{p:P({ln:[25,0],base:30}),pr:[{t:"box",at:"aF",dx:-26,w:36,h:30}],l:"1. Pas dans le vide"},{p:P({t:4,an:[172,176],af:[168,174],fn:40,ff:40,air:22}),pr:[{t:"box",at:"aN",dx:-64,w:36,h:30}],ar:[{at:"hip",o:[22,10],d:[0,-28]}],l:"2. Rebond immédiat"}]},
/* ---------- DÉPLACEMENTS ---------- */
star_drill:{n:"Drill étoile 5 cônes",c:"Déplacements",m:["Appuis","Cardio"],
 w:"Recrée les déplacements courts du padel : split-step, départ, retour au centre.",
 s:["Place 5 cônes en demi-étoile à 3 m d'un point central, comme sur le schéma.","Split-step au centre, puis va toucher le cône 1 en pas chassés ou en course.","Reviens au centre, split-step, et repars vers le cône suivant.","Enchaîne les 5 cônes pendant la durée indiquée. C'est aussi le « spider drill » des tests."],
 k:["Split-step à chaque retour","Centre de gravité bas"],e:["Se redresser entre deux cônes","Croiser les pieds en pas chassés"],ez:"Moins vite, qualité des appuis.",hd:"Un partenaire désigne le cône au dernier moment.",
 fig:[{court:{player:[5,7.6],cones:[[2,7.6],[2.9,5.5],[5,4.6],[7.1,5.5],[8,7.6]],spokes:true},l:"Aller-retour vers chaque cône (3 m)"}]},
left_drill:{n:"Drill gauche : vitre → filet → smash",c:"Déplacements",m:["Appuis","Cardio"],
 w:"L'enchaînement typique du joueur de gauche : défendre au fond, prendre le filet, finir au smash.",
 s:["Pars en défense au fond, côté gauche.","1. Déplacement vers le coin pour une sortie de vitre (geste en shadow).","2. Sprint vers le filet, split-step, volée en shadow.","3. Recul en pas croisés pour un smash simulé. 4. Retour en défense."],
 k:["Intensité de match","Split-step à chaque changement"],e:["Reculer en courant de dos","Oublier le geste en shadow"],ez:"Sans le smash.",hd:"Avec raquette et un partenaire qui lance.",
 fig:[{court:{side:true,player:[3.3,8.8],segs:[{a:[3.3,8.8],b:[1.1,9.2],n:1},{a:[1.1,9.2],b:[2.6,2.3],n:2},{a:[2.6,2.3],b:[3,5],n:3},{a:[3,5],b:[3.3,8.8],n:4}],marks:[{p:[1.1,9.2],t:"vitre",dx:0,dy:-12,anc:"middle"},{p:[2.6,2.3],t:"volée",dx:10},{p:[3,5],t:"smash",dx:10}]},l:"Côté gauche, 15 s d'effort"}]},
left_drill_full:{n:"Drill gauche complet",c:"Déplacements",m:["Appuis","Cardio"],
 w:"Toute la séquence d'un point côté gauche, à vitesse de match.",
 s:["Pars au filet : volée en shadow.","1. Recul pour une bandeja ou une víbora.","2. Recul en pas croisés jusqu'en défense au fond.","3. Sortie de vitre dans le coin, puis 4. remontée au filet."],
 k:["Pas croisés en recul","Geste complet à chaque coup"],e:["Tourner le dos au filet"],ez:"Moins vite.",hd:"Partenaire qui lance des balles.",
 fig:[{court:{side:true,player:[2.6,2.3],segs:[{a:[2.6,2.3],b:[3,4.9],n:1},{a:[3,4.9],b:[3.4,8.8],n:2},{a:[3.4,8.8],b:[1.1,9.2],n:3},{a:[1.1,9.2],b:[2.6,2.3],n:4}],marks:[{p:[2.6,2.3],t:"volée",dx:10},{p:[3,4.9],t:"bandeja",dx:10},{p:[3.4,8.8],t:"défense",dx:10},{p:[1.1,9.2],t:"vitre",dx:0,dy:-12,anc:"middle"}]},l:"Côté gauche, 20 s d'effort"}]},
reactive_acc:{n:"Accélérations réactives 5 m",c:"Déplacements",m:["Appuis","Vitesse"],
 w:"Réagir à un signal comme à une balle : démarrage explosif dans toutes les directions.",
 s:["Place 4 cônes à 5 m de toi : devant, derrière, à gauche, à droite.","Position de split-step ; un partenaire annonce une direction ou la montre du doigt.","Sprint jusqu'au cône le plus vite possible.","Reviens en marchant, récupère 30 s, recommence."],
 k:["Premier pas explosif","Pas d'anticipation"],e:["Se relever avant de partir"],ez:"Direction annoncée à l'avance.",hd:"Signal visuel (le partenaire montre une couleur).",
 fig:[{court:{plain:true,lab:"cônes à 5 m",player:[5,5],cones:[[5,0.6],[9.4,5],[5,9.4],[0.6,5]],spokes:true},l:"Départ au signal, 4 directions"}]},
/* ---------- CARDIO ---------- */
int_3030:{n:"Intervalles 30/30",c:"Cardio",m:["Cardio","Endurance"],
 w:"Augmente ton endurance à haute intensité et accélère la perte de poids.",
 s:["Sur vélo, rameur ou en course.","30 s à haute intensité (8/10), puis 30 s très calme.","6 répétitions, 3 min de récupération, puis deuxième série.","L'intensité doit être la même du premier au dernier."],
 k:["Régularité"],e:["Partir trop fort"],ez:"5 répétitions.",hd:"8 répétitions.",
 fig:[{tl:{w:30,r:30,n:6,sets:2,sr:"3 min"},l:"Une série"}]},
int_points:{n:"Intervalles « points de padel » 15/25",c:"Cardio",m:["Cardio","Appuis"],
 w:"Un point de padel dure en moyenne 10 à 20 s. Ce format reproduit l'effort d'un match.",
 s:["Sur le terrain de préférence.","15 s d'effort maximal : pas chassés, montées, reculs, gestes en shadow.","25 s de récupération en marchant.","8 répétitions, 3 min de repos, 3 séries."],
 k:["Vitesse de match"],e:["Récupération active trop intense"],ez:"6 répétitions.",hd:"10 répétitions.",
 fig:[{tl:{w:15,r:25,n:8,sets:3,sr:"3 min",lab1:"effort max (point)"},l:"Une série"}]},
rsa:{n:"Répétitions de sprints 20/20",c:"Cardio",m:["Cardio","Vitesse"],
 w:"Travaille la capacité à répéter des efforts intenses : celle qui fait la différence dans un 3e set.",
 s:["Sur le terrain ou une piste.","20 s de déplacements à vitesse maximale (sprints courts, changements de direction).","20 s de récupération en marchant.","8 répétitions, 4 min de repos, 2 séries."],
 k:["Chaque répétition à fond"],e:["Ralentir en fin de série sans le noter"],ez:"6 répétitions.",hd:"3 séries.",
 fig:[{tl:{w:20,r:20,n:8,sets:2,sr:"4 min",lab1:"sprint max"},l:"Une série"}]},
zone2:{n:"Cardio zone 2",c:"Cardio",m:["Cœur","Endurance"],
 w:"Construit ta base d'endurance, aide à récupérer du tournoi et brûle des graisses sans fatiguer les jambes.",
 s:["Choisis vélo, rameur, marche rapide inclinée ou footing lent.","Intensité où tu peux tenir une conversation : environ 120 à 135 battements par minute pour toi.","Tiens 30 à 40 minutes en continu.","Enchaîne avec la routine de mobilité."],
 k:["Tu dois pouvoir parler en phrases complètes"],e:["Aller trop vite : ce n'est plus de la zone 2"],ez:"20 minutes.",hd:"45 minutes.",
 fig:[{p:P({t:22,ln:[72,-20],lf:[34,-4],an:[62,95],af:[58,95],base:24}),pr:[{t:"bike"}],l:"Rythme conversation"}]},
/* ---------- MOBILITÉ ---------- */
m_catcow:{n:"Chat-vache",c:"Mobilité",m:["Colonne vertébrale"],
 w:"Mobilise toute la colonne en douceur, idéal au réveil ou avant de jouer.",
 s:["À quatre pattes, mains sous les épaules, genoux sous les hanches.","Chat : expire en arrondissant le dos vers le plafond, menton vers la poitrine.","Vache : inspire en creusant doucement le dos, regard vers l'avant.","Alterne lentement, vertèbre par vertèbre."],
 fig:[{p:P({...QUAD,arch:10,hd:60}),l:"Chat : dos rond"},{p:P({...QUAD,arch:-8,hd:-40}),l:"Vache : dos creusé"}]},
m_thoracic:{n:"Rotation thoracique à quatre pattes",c:"Mobilité",m:["Haut du dos"],
 w:"La rotation du haut du dos permet de frapper sans forcer sur les lombaires ni sur l'épaule.",
 s:["À quatre pattes, une main derrière la tête.","Fais descendre le coude vers le poignet opposé.","Ouvre ensuite en tournant le buste, coude vers le plafond, le regard suit.","Le bassin reste immobile. 6 fois, puis change de côté."],
 fig:[{p:P({...QUAD,an:[18,140]}),l:"Coude vers le poignet"},{p:P({...QUAD,an:[-178,40]}),ar:[{at:"eN",o:[14,6],d:[0,-22]}],l:"Coude vers le plafond"}]},
m_wgs:{n:"Fente avec rotation",c:"Mobilité",m:["Hanches","Ischios","Haut du dos"],
 w:"Ouvre hanches, ischios et haut du dos en un seul mouvement (le « world's greatest stretch »).",
 s:["Grande fente avant, genou arrière tendu ou posé.","Main du côté de la jambe avant au sol, à l'intérieur du pied.","Tourne le buste et lève l'autre bras vers le plafond, regard sur la main.","Reviens, puis tends la jambe avant pour étirer l'ischio. Change de côté."],
 fig:[{p:P({t:72,ln:[86,-2],lf:[-62,-62],ff:20,an:[2,2],af:[0,0]}),l:"Fente, mains au sol"},{p:P({t:72,ln:[86,-2],lf:[-62,-62],ff:20,an:[178,178],af:[0,0]}),ar:[{at:"eN",o:[14,0],d:[0,-20]}],l:"Bras vers le plafond"}]},
m_9090:{n:"Hanches 90/90",c:"Mobilité",m:["Hanches"],
 w:"Rotations interne et externe de hanche, indispensables pour pivoter vite sur le terrain.",
 s:["Assis au sol, jambe avant pliée à 90° devant toi, jambe arrière pliée à 90° sur le côté.","Buste droit, penche-toi légèrement au-dessus du tibia avant.","Fais basculer les deux genoux de l'autre côté, comme un essuie-glace, sans les mains si possible.","Retrouve la position 90/90 de l'autre côté."],
 fig:[{top:{rot:0,legs:[[[-8,8],[-8,-30],[26,-30]],[[8,8],[44,8],[44,42]]]},l:"90/90 à droite"},{top:{rot:0,legs:[[[8,8],[8,-30],[-26,-30]],[[-8,8],[-44,8],[-44,42]]],ar:[[[-30,-44],[30,-44],[0,-60]]]},l:"Bascule : 90/90 à gauche"}]},
m_hipflexor:{n:"Étirement des fléchisseurs de hanche",c:"Mobilité",m:["Psoas","Quadriceps"],
 w:"Assis toute la journée, ces muscles se raccourcissent et limitent ta foulée et ta détente.",
 s:["Un genou au sol, l'autre pied devant, genoux à 90°.","Serre le fessier de la jambe arrière et rentre légèrement le bassin.","Avance doucement le bassin jusqu'à sentir l'étirement devant la hanche.","Lève le bras du côté de la jambe arrière pour accentuer."],
 fig:[{p:P({t:-6,ln:[86,-2],lf:[-4,-92],ff:-90,an:[180,178],af:[-20,60]}),ar:[{at:"hip",o:[-6,10],d:[18,0]}],l:"Bassin vers l'avant"}]},
m_frog:{n:"Bascule adducteurs",c:"Mobilité",m:["Adducteurs"],
 w:"Assouplit les adducteurs pour les grands écarts en défense.",
 s:["À quatre pattes sur les avant-bras, genoux très écartés, pieds vers l'extérieur.","Pieds et genoux à la même hauteur.","Recule doucement les fesses vers l'arrière jusqu'à sentir l'étirement à l'intérieur des cuisses.","Reviens en avant et répète lentement."],
 fig:[{p:P({t:104,ln:[0,-90],lf:[4,-90],fn:-90,ff:-90,an:[0,90],af:[0,90]}),l:"Genoux écartés"},{p:P({t:116,ln:[48,-90],lf:[44,-90],fn:-90,ff:-90,an:[-12,90],af:[-12,90]}),ar:[{at:"hip",o:[4,-14],d:[-20,0]}],l:"Fesses vers l'arrière"}]},
m_ankle:{n:"Mobilité de cheville au mur",c:"Mobilité",m:["Chevilles","Mollets"],
 w:"Une cheville mobile, c'est des appuis plus bas et des genoux protégés.",
 s:["Un genou au sol, pied avant à 5–10 cm du mur.","Talon collé au sol, pousse le genou vers le mur dans l'axe du 2e orteil.","Touche le mur, reviens. 10 fois.","Si c'est facile, recule le pied de 1–2 cm."],
 fig:[{p:P({t:0,ln:[82,0],lf:[-4,-92],ff:-90,an:[62,100],af:[58,100]}),pr:[{t:"wall",at:"aN",dx:30}],l:"Talon au sol"},{p:P({t:4,ln:[70,-26],lf:[-4,-92],ff:-90,an:[64,100],af:[60,100]}),pr:[{t:"wall",at:"aN",dx:30}],ar:[{at:"kN",o:[0,-12],d:[14,0]}],l:"Genou vers le mur"}]},
m_dislocate:{n:"Passages d'épaules à l'élastique",c:"Mobilité",m:["Épaules","Pectoraux"],
 w:"Mobilité complète des épaules, parfait avant de smasher.",
 s:["Tiens un élastique ou un bâton à deux mains, prise très large, bras tendus devant les cuisses.","Monte les bras tendus au-dessus de la tête.","Continue derrière le dos si ton épaule le permet, puis reviens.","Resserre la prise au fil des semaines."],
 fig:[{p:P({view:"front",ln:[-4,0],lf:[4,0],an:[-35,-35],af:[35,35]}),pr:[{t:"line",a:"hN",b:"hF"}],l:"Prise large, bras devant"},{p:P({view:"front",ln:[-4,0],lf:[4,0],an:[-150,-150],af:[150,150]}),pr:[{t:"line",a:"hN",b:"hF"}],ar:[{at:"shF",o:[30,20],d:[0,-34]}],l:"Au-dessus, puis derrière le dos"}]},
m_wrist:{n:"Étirement poignets et avant-bras",c:"Mobilité",m:["Avant-bras","Coude"],
 w:"Prévient les douleurs de coude (épicondylite), fréquentes au padel.",
 s:["Bras tendu devant toi, paume vers l'avant, doigts vers le haut.","Avec l'autre main, tire doucement les doigts vers toi : 30 s.","Retourne la main, doigts vers le bas, et tire doucement : 30 s.","Fais les deux bras."],
 fig:[{p:P({an:[90,90],hn:175,af:[60,108]}),l:"Doigts vers le haut"},{p:P({an:[90,90],hn:5,af:[60,108]}),l:"Doigts vers le bas"}]},
m_sleeper:{n:"Sleeper stretch",c:"Mobilité",m:["Épaule (rotation interne)"],
 w:"Garde la rotation interne de l'épaule, qui diminue avec les smashs répétés.",
 s:["Allongé sur le côté de l'épaule à étirer, bras devant toi à 90°, coude plié à 90°, doigts vers le plafond.","Avec l'autre main, pousse doucement le poignet vers le sol.","Arrête-toi à la première tension, jamais de douleur.","Tiens 30 s, 2 fois."],
 fig:[{p:P({t:90,ln:[-90,-90],lf:[-90,-90],fn:-90,ff:-90,an:[0,180],anS:[0.3,1],af:[-150,-60]}),l:"Avant-bras vertical"},{p:P({t:90,ln:[-90,-90],lf:[-90,-90],fn:-90,ff:-90,an:[0,-110],anS:[0.3,1],af:[-150,-100]}),ar:[{at:"eN",o:[-4,-26],d:[-20,12],c:[-18,-6]}],l:"Poignet poussé vers le sol"}]},
m_roller:{n:"Rouleau de massage",c:"Mobilité",m:["Mollets","Quadriceps","Dos"],
 w:"Détend mollets, quadriceps et dos après le tournoi.",
 s:["Assis, rouleau sous les mollets, mains au sol derrière toi.","Roule lentement de la cheville au genou pendant 1 min.","Passe aux quadriceps (sur le ventre) puis au haut du dos.","Insiste 20–30 s sur les zones tendues, sans douleur vive."],
 fig:[{p:P({t:-55,ln:[88,90],lf:[86,90],fn:180,ff:180,an:[-30,-20],af:[-26,-20]}),pr:[{t:"roller",a:"kN",b:"aN"}],ar:[{at:"kN",o:[6,-14],d:[20,0]}],l:"Rouler du genou à la cheville"}]}
};

/* Exercices « version maison » */
Object.assign(EX,{
row_band:{n:"Rowing à l'élastique",c:"Force",m:["Grand dorsal","Rhomboïdes","Biceps"],
 w:"Remplace le rowing haltère et les tractions quand tu n'as pas de salle : même travail du dos et de l'omoplate.",
 s:["Accroche l'élastique à une poignée de porte fermée (ou autour d'un poteau), à hauteur de poitrine.","Recule jusqu'à ce que l'élastique soit tendu, genoux légèrement fléchis, buste droit.","Tire les coudes vers l'arrière le long du corps jusqu'à amener les mains aux côtes.","Serre les omoplates 1 s, puis reviens lentement en 2 s."],
 k:["Épaules basses","Retour lent"],e:["Tirer avec les poignets","Se pencher en arrière"],ez:"Élastique plus léger.",hd:"Un bras à la fois.",
 fig:[{p:P({t:4,ln:[10,-6],lf:[6,-4],an:[80,90],af:[76,90]}),pr:[{t:"band",from:"hN",d:[60,0]}],l:"Bras tendus"},{p:P({t:4,ln:[10,-6],lf:[6,-4],an:[-30,85],af:[-34,85]}),pr:[{t:"band",from:"hN",d:[76,0]}],ar:[{at:"hN",o:[20,-12],d:[-18,0]}],l:"Coudes en arrière"}]},
rot_band:{n:"Rotation à l'élastique",c:"Explosivité",m:["Obliques","Hanches"],
 w:"Remplace la landmine et le lancer de médecine-ball : rotation qui part des hanches, comme tes frappes.",
 s:["Élastique accroché à hauteur de poitrine, place-toi de profil, bras tendus devant toi.","Pieds largeur d'épaules, genoux légèrement fléchis.","Tourne les hanches puis le buste pour amener les mains de l'autre côté, en pivotant le pied arrière.","Reviens en contrôlant. Version explosive : aller rapide, retour lent."],
 k:["Les hanches lancent le mouvement","Bras quasi tendus"],e:["Tourner seulement les bras"],ez:"Élastique plus léger.",hd:"Aller le plus vite possible.",
 fig:[{top:{rot:-30,to:[-26,-30],band:[-86,-30]},l:"Départ côté ancrage"},{top:{rot:40,to:[32,-24],band:[-86,-30],ar:[[[-22,-6],[28,-4],[4,16]]]},l:"Rotation des hanches"}]},
burpee:{n:"Burpee",c:"Cardio",m:["Tout le corps","Cardio"],
 w:"Remplace le slam ball à la maison : puissance et cardio en un seul mouvement.",
 s:["Debout, descends en squat et pose les mains au sol.","Saute les pieds en arrière en position de pompe.","Ramène les pieds sous toi d'un saut.","Relève-toi en sautant, bras au-dessus de la tête."],
 k:["Dos gainé en position de pompe","Rythme régulier"],e:["Bassin qui s'effondre"],ez:"Sans le saut, en marchant les pieds.",hd:"Ajoute une pompe.",
 fig:[{p:P({t:60,ln:[80,-40],lf:[76,-38],an:[5,5],af:[3,3]}),l:"Mains au sol"},{p:P({t:80,ln:[-62,-62],lf:[-62,-62],fn:0,ff:0}),l:"Pieds en arrière"}]}
});
/* Requêtes de recherche vidéo (démonstrations YouTube) */
const VQ={squat_goblet:"goblet squat technique",back_squat:"back squat technique débutant",contrast_squat:"contrast training squat jump",rdl:"romanian deadlift dumbbell technique",trapbar:"trap bar deadlift technique",lunge_back:"reverse lunge dumbbell technique",jump_lunge:"jump lunge technique",bulgarian:"bulgarian split squat technique",row_db:"one arm dumbbell row technique",bench_db:"dumbbell bench press technique",pullup:"pull up technique beginner",press_1arm:"single arm dumbbell overhead press",push_press:"dumbbell push press technique",landmine:"landmine rotation exercise",pallof:"pallof press technique",plank:"plank technique",side_plank:"side plank technique",side_plank_rot:"side plank thread the needle",dead_bug:"dead bug exercise technique",shoulder_tap:"plank shoulder taps",pushup:"push up technique",ext_rot:"band external rotation shoulder",ext_rot90:"90 90 external rotation band",ytw:"YTW incline bench exercise",copenhagen:"copenhagen plank",calf_ecc:"eccentric calf raise achilles",rope:"jump rope basics",pogo:"pogo jumps",box_jump:"box jump technique",skater:"skater jumps",mb_rot:"rotational medicine ball throw",mb_slam:"medicine ball slam technique",mb_overhead:"overhead medicine ball throw jump",cmj:"countermovement jump technique",depth_jump:"depth jump technique",star_drill:"padel footwork drill",left_drill:"padel ejercicios desplazamientos",left_drill_full:"padel footwork drill bandeja defense",reactive_acc:"reactive agility drill",int_3030:"30 30 interval training",int_points:"padel conditioning drills",rsa:"repeated sprint ability training",zone2:"zone 2 cardio explained",m_catcow:"cat cow stretch",m_thoracic:"quadruped thoracic rotation",m_wgs:"world's greatest stretch",m_9090:"90 90 hip switch",m_hipflexor:"half kneeling hip flexor stretch",m_frog:"frog stretch rock back",m_ankle:"knee to wall ankle mobility",m_dislocate:"band shoulder dislocates",m_wrist:"wrist flexor extensor stretch",m_sleeper:"sleeper stretch",m_roller:"foam roller calves quads",row_band:"resistance band row door",rot_band:"band rotation core",burpee:"burpee technique"};
Object.keys(VQ).forEach(k=>{if(EX[k])EX[k].vq=VQ[k];});
/* Charges : exercices où l'on note des kilos */
const LOADED=new Set(["squat_goblet","back_squat","contrast_squat","rdl","trapbar","lunge_back","bulgarian","row_db","bench_db","pullup","press_1arm","push_press","landmine","mb_rot","mb_slam","mb_overhead","calf_ecc","ytw"]);
const BIG_LIFTS=new Set(["back_squat","trapbar","contrast_squat","rdl","bulgarian"]);
